
import insert from table
import Set from require "moonscript.data"
import Block from require "moonscript.compile"
import ntype from require "moonscript.types"

import mtype from require "moonscript.util"

-- globals allowed to be referenced
default_whitelist = Set {
  '_G'
  '_VERSION'
  'assert'
  'bit32'
  'collectgarbage'
  'coroutine'
  'debug'
  'dofile'
  'error'
  'getfenv'
  'getmetatable'
  'io'
  'ipairs'
  'load'
  'loadfile'
  'loadstring'
  'math'
  'module'
  'next'
  'os'
  'package'
  'pairs'
  'pcall'
  'print'
  'rawequal'
  'rawget'
  'rawlen'
  'rawset'
  'require'
  'select'
  'setfenv'
  'setmetatable'
  'string'
  'table'
  'tonumber'
  'tostring'
  'type'
  'unpack'
  'xpcall'

  "nil"
  "true"
  "false"
}

-- the named checks that can be enabled or disabled when linting
LINT_STAGES = {
  "global_access"
  "unused"
  "constant_assign"
  "import_overwrite"
}

class LinterBlock extends Block
  new: (whitelist_globals=default_whitelist, stages, ...) =>
    super ...
    @lint_errors = {}

    if stages
      @lint_stages = Set stages

    @lint_wrap_transform = (block) =>
      inner = block.transform.statement
      checked_imports = setmetatable {}, __mode: "k"

      block.transform.statement = (node, ...) ->
        import_node = node
        while ntype(import_node) == "transform"
          import_node = import_node[2]

        if ntype(import_node) == "import" and not checked_imports[import_node]
          checked_imports[import_node] = true

          for name in *import_node[2]
            name = name[2] if ntype(name) == "colon"
            binding = block\binding_value name

            -- repeated imports are reported by the constant assignment
            -- check after the import is lowered
            unless type(binding) == "table" and binding.const
              if binding
                block.root\lint_report "import_overwrite",
                  "import overwrites existing binding `#{name}`", import_node[-1]

        inner node, ...
      block

    @lint_wrap_transform @

    vc = @value_compilers
    @value_compilers = setmetatable {
      ref: (block, val) ->
        name = val[2]
        unless block\has_name(name) or whitelist_globals[name] or name\match "%."
          @lint_report "global_access", "accessing global `#{name}`", val[-1]

        block\lint_mark_used name
        vc.ref block, val
    }, __index: vc

    sc = @statement_compilers
    @statement_compilers = setmetatable {
      assign: (block, node) ->
        names = node[2]

        -- extract the names to be declared
        for name in *names
          -- don't include autogenerated names
          if type(name) == "table" and name[1] == "temp_name"
            continue

          const_name = if type(name) == "string"
            name
          elseif name[1] == "ref"
            name[2]

          if const_name
            binding = block\binding_value const_name
            if type(binding) == "table" and binding.const
              @lint_report "constant_assign", "assigning to constant `#{const_name}`",
                type(name) == "table" and name[-1] or node[-1] or block.root.last_pos

          real_name, is_local = block\extract_assign_name name
          -- already defined in some other scope
          unless is_local or real_name and not block\has_name real_name, true
            continue

          continue if real_name == "_"

          block.lint_unused_names or= {}
          block.lint_unused_names[real_name] = node[-1] or 0

        sc.assign block, node
    }, __index: sc

  -- records an error if the stage is enabled
  lint_report: (stage, msg, pos) =>
    root = @root
    return if root.lint_stages and not root.lint_stages[stage]
    insert root.lint_errors, {msg, pos, stage}

  lint_mark_used: (name) =>
    if @lint_unused_names and @lint_unused_names[name]
      @lint_unused_names[name] = false
      return

    if @parent
      @parent\lint_mark_used name

  lint_check_unused: =>
    return unless @lint_unused_names and next @lint_unused_names

    names_by_position = {}
    for name, pos in pairs @lint_unused_names
      continue unless pos
      names_by_position[pos] or= {}
      insert names_by_position[pos], name

    tuples = [{pos, names} for pos,names in pairs names_by_position]
    table.sort tuples, (a,b) -> a[1] < b[1]

    for {pos, names} in *tuples
      @root\lint_report "unused",
        "assigned but unused #{table.concat ["`#{n}`" for n in *names], ", "}", pos

  render: (...) =>
    @lint_check_unused!
    super ...

  block: (...) =>

    with child = super ...
      .block = @block
      .render = @render
      .lint_check_unused = @lint_check_unused
      .lint_mark_used = @lint_mark_used
      .value_compilers = @value_compilers
      .statement_compilers = @statement_compilers
      .lint_wrap_transform = @lint_wrap_transform
      @lint_wrap_transform child

-- one `file:line:col: message [stage]` line per error
format_lint_compact = (errors, code, header) ->
  return nil unless next errors

  import pos_to_line_col from require "moonscript.util"
  formatted = for {msg, pos, stage} in *errors
    location = if pos
      line, col = pos_to_line_col code, pos
      "#{header}:#{line}:#{col}"
    else
      header

    stage_suffix = stage and " [#{stage}]" or ""
    "#{location}: #{msg}#{stage_suffix}"

  table.concat formatted, "\n"

format_lint = (errors, code, header) ->
  return unless next errors

  import pos_to_line, get_line from require "moonscript.util"
  formatted = for {msg, pos} in *errors
    if pos
      line = pos_to_line code, pos
      msg = "line #{line}: #{msg}"
      line_text = "> " .. get_line code, line

      sep_len = math.max #msg, #line_text
      table.concat {
        msg
        "="\rep sep_len
        line_text
      }, "\n"

    else
      msg

  table.insert formatted, 1, header if header
  table.concat formatted, "\n\n"


-- {
--   whitelist_globals: {
--     ["some_file_pattern"]: {
--       "some_var", "another_var"
--     }
--   }
-- }
whitelist_for_file = do
  local lint_config
  (fname) ->
    unless lint_config
      lint_config = {}
      pcall -> lint_config = require "lint_config"

    return default_whitelist unless lint_config.whitelist_globals
    final_list = {}
    for pattern, list in pairs lint_config.whitelist_globals
      if fname\match(pattern)
        for item in *list
          insert final_list, item

    setmetatable Set(final_list), __index: default_whitelist

-- the named output formats for lint results
LINT_FORMATS = {"default", "compact"}

formatters = {
  default: format_lint
  compact: format_lint_compact
}

-- opts: {stages: {stage_name}, format: format_name}
lint_code = (code, name="string input", whitelist_globals, opts) ->
  parse = require "moonscript.parse"
  tree, err = parse.string code
  return nil, err unless tree

  scope = LinterBlock whitelist_globals, opts and opts.stages
  scope\stms tree
  scope\lint_check_unused!

  formatter = formatters[opts and opts.format or "default"]
  error "unknown lint format: #{opts.format}" unless formatter
  formatter scope.lint_errors, code, name

lint_file = (fname, opts) ->
  f, err = io.open fname
  return nil, err unless f
  lint_code f\read("*a"), fname, whitelist_for_file(fname), opts


{ :lint_code, :lint_file, :LINT_STAGES, :LINT_FORMATS }
